/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Entidades.Alumnos;
import java.sql.Date;
import javax.swing.JTextField;
import Entidades.AlumnosDAO;
import java.awt.Component;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author GIAN
 */
public class FrameModificar extends javax.swing.JFrame {
    FrameListaAlumnos padre;
    AlumnosDAO alumnosDao = new AlumnosDAO();
    /**
     * Creates new form FrameModificar
     */
    
    public FrameModificar(int codigo, String nombre, int telefono, String especialidad, String docente, Date fecha, String departamento, String provincia, int edad, String sexo){
        initComponents();
        txtdniM.setEnabled(false);
        txtdniM.setText(Integer.toString(codigo));
        txtnombreM.setText(nombre);
        txtTelefonoM.setText(Integer.toString(telefono));
        cbEspecialidadM.setSelectedItem(especialidad);
        cbDocenteM.setSelectedItem(docente);
        jdcFechaM.setDate(fecha);                  
        txtDepartamentoM.setText(departamento);
        txtProvinciaM.setText(provincia);
        txtEdadM.setText(Integer.toString(edad));
        if("M".equals(sexo)) {
            MrbF.setSelected(true);
            MrbM.setSelected(false);
        }else if("H".equals(sexo)){ 
            MrbF.setSelected(false);
            MrbM.setSelected(true);
        }else{
            MrbF.setSelected(false);
            MrbM.setSelected(false);
        }
        //this.padre = padre;
        rsscalelabel.RSScaleLabel.setScaleLabel(lblLogo,"src/Imagenes/Logo.png");
    }

    private FrameModificar(/*FrameListaAlumnos padre*/) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        //this.padre = padre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtdniM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnombreM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jdcFechaM = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        txtDepartamentoM = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefonoM = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        MrbM = new javax.swing.JRadioButton();
        MrbF = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtProvinciaM = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbDocenteM = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbEspecialidadM = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtEdadM = new javax.swing.JTextField();
        btnRegresarM = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bg.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setText("DNI");

        jLabel3.setText("NOMBRE");

        txtnombreM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreMActionPerformed(evt);
            }
        });

        jLabel1.setText("FECHA");

        jdcFechaM.setDateFormatString("yyyy-MM-dd");

        jLabel4.setText("DEPARTAMENTO");

        jLabel5.setText("TELEFONO");

        jLabel10.setText("SEXO");

        MrbM.setText("Hombre");

        MrbF.setText("Mujer");
        MrbF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MrbFActionPerformed(evt);
            }
        });

        jLabel9.setText("PROVINCIA");

        jLabel8.setText("DOCENTE");

        cbDocenteM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Olivia Apaza", "Mario Soledad" }));

        jLabel6.setText("ESPECIALIDAD");

        cbEspecialidadM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Confeccion Textil", "Construcciones Metalicas" }));

        jLabel7.setText("EDAD");

        btnRegresarM.setText("<<<Regresar");
        btnRegresarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("MODIFICAR DATOS ALUMNOS");

        javax.swing.GroupLayout BgLayout = new javax.swing.GroupLayout(Bg);
        Bg.setLayout(BgLayout);
        BgLayout.setHorizontalGroup(
            BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BgLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnRegresarM, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BgLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BgLayout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addGroup(BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtdniM, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                        .addComponent(txtTelefonoM)
                        .addComponent(txtnombreM, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                        .addComponent(txtDepartamentoM, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                        .addComponent(jdcFechaM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(80, 80, 80)
                    .addGroup(BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BgLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(20, 20, 20))
                            .addGroup(BgLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(29, 29, 29)))
                        .addComponent(jLabel6)
                        .addComponent(jLabel10)
                        .addComponent(jLabel7))
                    .addGap(29, 29, 29)
                    .addGroup(BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtEdadM)
                        .addComponent(cbEspecialidadM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtProvinciaM)
                        .addComponent(cbDocenteM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BgLayout.createSequentialGroup()
                            .addComponent(MrbM)
                            .addGap(37, 37, 37)
                            .addComponent(MrbF)))
                    .addContainerGap(37, Short.MAX_VALUE)))
        );
        BgLayout.setVerticalGroup(
            BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BgLayout.createSequentialGroup()
                .addGroup(BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BgLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel11))
                    .addGroup(BgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 369, Short.MAX_VALUE)
                .addGroup(BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarM, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BgLayout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addGroup(BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel7)
                        .addComponent(txtdniM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEdadM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(34, 34, 34)
                    .addGroup(BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6)
                        .addComponent(txtnombreM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbEspecialidadM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(25, 25, 25)
                    .addGroup(BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(cbDocenteM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jdcFechaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(34, 34, 34)
                    .addGroup(BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel9)
                        .addComponent(txtDepartamentoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtProvinciaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(33, 33, 33)
                    .addGroup(BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel10)
                        .addComponent(txtTelefonoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MrbM)
                        .addComponent(MrbF))
                    .addContainerGap(127, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreMActionPerformed

    private void MrbFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MrbFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MrbFActionPerformed

    private void btnRegresarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMActionPerformed
        txtdniM.setEnabled(true);
        FrameListaAlumnos Main = new FrameListaAlumnos();
        Main.setLocationRelativeTo(this);
        Main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarMActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        try{
            //Imagen
            ImageIcon icono = new ImageIcon("src/Imagenes/check.png");
            //Ajustar dimenciones del icono 
            int x = 100;
            int y = 100;
            Image ScalaImagen = icono.getImage().getScaledInstance(y, x, Image.SCALE_SMOOTH);
            ImageIcon ScaledIcon = new ImageIcon(ScalaImagen);
            
            //Obtener el componente de la ventana principal
            Component parentComponent = this;
           
            int codigo = Integer.parseInt(txtdniM.getText());
            String nombre = txtnombreM.getText();
            int telefono = Integer.parseInt(txtTelefonoM.getText());
            String especialidad = cbEspecialidadM.getSelectedItem().toString();
            String docente = cbDocenteM.getSelectedItem().toString();   
            String fecha = ((JTextField)jdcFechaM.getDateEditor().getUiComponent()).getText();
            String departamento = txtDepartamentoM.getText();
            String provincia = txtProvinciaM.getText();
            String sexo;
            if(MrbF.isSelected() == true){ //F = Femenino -> M = Mujer
                sexo = "M";
            }else if(MrbM.isSelected() == true){ //M = Masculino -> H = Hombre
                sexo = "H";
            }else{
                sexo = "N";
            }
            int edad = Integer.parseInt(txtEdadM.getText());
            Alumnos alumno = new Alumnos(codigo,nombre,telefono,especialidad,docente,Date.valueOf(fecha),departamento,provincia,edad,sexo);
            //Metodo "Update" del AlumnosDAO 
            alumnosDao.Uptade(alumno);
            //Actualizamos La Tabla
            //padre.actulizarTable();
            JOptionPane.showMessageDialog(parentComponent, "Se Modifico Correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE,ScaledIcon);            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error al Modificar", "Error", JOptionPane.ERROR_MESSAGE);         
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameModificar(/*new FrameListaAlumnos()*/).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg;
    private javax.swing.JRadioButton MrbF;
    private javax.swing.JRadioButton MrbM;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresarM;
    private javax.swing.JComboBox<String> cbDocenteM;
    private javax.swing.JComboBox<String> cbEspecialidadM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser jdcFechaM;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTextField txtDepartamentoM;
    private javax.swing.JTextField txtEdadM;
    private javax.swing.JTextField txtProvinciaM;
    private javax.swing.JTextField txtTelefonoM;
    private javax.swing.JTextField txtdniM;
    private javax.swing.JTextField txtnombreM;
    // End of variables declaration//GEN-END:variables
}
